name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actalog/check-ci@7ac8446036b5fec39d2eea4d8f61b40c27de3c79
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: '@servicespack'
      - run: npm ci
      - run: npm run build
      - run: npm publish --workspaces --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
