name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@14833cab3493c139c8048351f8166540b8051a46

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
